spring:
    profiles.active: dev

---
spring:
    profiles: dev

    datasource:
        url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa.database-platform: org.hibernate.dialect.H2Dialect

    jpa.hibernate.ddl-auto: create-drop

---
spring:
    profiles: devMySQL

    datasource:
        url: jdbc:mysql://localhost:3306/itcareer?autoReconnect=true&amp;useUnicode=true&amp;createDatabaseIfNotExist=true&amp;characterEncoding=UTF-8
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        connection-properties: useUnicode=true;characterEncoding=utf-8

    jpa.database-platform: org.hibernate.dialect.MySQL5Dialect

    jpa:
        show-sql: true
        hibernate.ddl-auto: create-drop

# Pool
spring.datasource.max-active: 25
spring.datasource.max-idle: 5
spring.datasource.min-idle: 5
spring.datasource.initial-size: 10